import tkinter as tk
root = tk.Tk()
root.geometry("700x700")
root.configure(bg='#28282B')
scrollbar = tk.Scrollbar(root)
root.title("Software Design")
frame1 = tk.Frame(root,bg="#50ad6f",width = 50)
title = tk.Label(frame1, text='Ecological Calculator',font=('Arial', 40,"bold"),fg = "white", bg="#50ad6f",width=50).pack(pady=20)
frame1.pack(pady=(40,0))
frame2 = tk.Frame(root,bg="#edede9",width=25)
frame2.pack(ipady=15)
motto = tk.Label(frame2,text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",font=('Arial',16),fg="black",width=125).pack(pady=10)

q1 = tk.Label(frame2,text="This will be determined later, so this is placeholder text in the place of Question 1",font=('Arial',16,"bold")).pack(pady=(10,10))
spinbox1 = tk.Spinbox(frame2, from_=0, to=10, width=10, relief="sunken", repeatdelay=300, repeatinterval=10,font=("Arial", 12))
spinbox1.pack()
q2 = tk.Label(frame2,text="This will be determined later, so this is placeholder text in the place of Question 2",font=('Arial',16,"bold")).pack(pady=(10,10))
spinbox2 = tk.Spinbox(frame2, from_=0, to=10, width=10, relief="sunken", repeatdelay=300, repeatinterval=10,font=("Arial", 12))
spinbox2.pack()
q3 = tk.Label(frame2,text="This will be determined later, so this is placeholder text in the place of Question 3",font=('Arial',16,"bold")).pack(pady=(10,10))
spinbox3 = tk.Spinbox(frame2, from_=0, to=10, width=10, relief="sunken", repeatdelay=300, repeatinterval=10,font=("Arial", 12))
spinbox3.pack()
q4 = tk.Label(frame2,text="This will be determined later, so this is placeholder text in the place of Question 4",font=('Arial',16,"bold")).pack(pady=(10,10))
spinbox4 = tk.Spinbox(frame2, from_=0, to=10, width=10, relief="sunken", repeatdelay=300, repeatinterval=10,font=("Arial", 12))
spinbox4.pack()
q5 = tk.Label(frame2,text="This will be determined later, so this is placeholder text in the place of Question 5",font=('Arial',16,"bold")).pack(pady=(10,10))
spinbox5 = tk.Spinbox(frame2, from_=0, to=10, width=10, relief="sunken", repeatdelay=300, repeatinterval=10,font=("Arial", 12))
spinbox5.pack()
q6 = tk.Label(frame2,text="This will be determined later, so this is placeholder text in the place of Question 6",font=('Arial',16,"bold")).pack(pady=(10,10))
spinbox6 = tk.Spinbox(frame2, from_=0, to=10, width=10, relief="sunken", repeatdelay=300, repeatinterval=10,font=("Arial", 12))
spinbox6.pack()
q7 = tk.Label(frame2,text="This will be determined later, so this is placeholder text in the place of Question 7",font=('Arial',16,"bold")).pack(pady=(10,10))
spinbox7 = tk.Spinbox(frame2, from_=0, to=10, width=10, relief="sunken", repeatdelay=300, repeatinterval=10,font=("Arial", 12))
spinbox7.pack()

def submit():
    answer = "You're EcoScore is " + str(int(spinbox1.get())+int(spinbox2.get())+int(spinbox3.get())+int(spinbox4.get())+int(spinbox5.get())+int(spinbox6.get())+int(spinbox7.get()))
    frame2.pack_forget()
    frame3 = tk.Frame(root,bg="#edede9")
    frame3.pack(ipady=30)
    text1 = tk.Label(frame3,text=answer,font =("Arial",30,"bold"),width=65)
    text1.pack(pady=20)
    info = tk.Label(frame3,text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", font=("Arial",16,"italic"))
    info.pack(pady=5)
    improve1 = tk.Label(frame3,text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut \nenim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor \nin reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, \nsunt in culpa qui officia deserunt mollit anim id est laborum.", font=("Arial",16,"italic"))
    improve1.pack(pady=5)
    improve2 = tk.Label(frame3,text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut \nenim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor \nin reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, \nsunt in culpa qui officia deserunt mollit anim id est laborum.", font=("Arial",16,"italic"))
    improve2.pack(pady=5)
    

submit = tk.Button(frame2, text="SUBMIT",font=('Arial',14,"bold"),bg="#00FF00",command=submit).pack(pady=(10,0),ipady=5)

root.mainloop()
